bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '0' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '7' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '9' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '13' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '17' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '23' #
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '30' #
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '40' #
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'EGF' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'full' -t '0' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '0' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '7' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '9' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '13' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '17' #
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '40' #
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iEGFR' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '0' #
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iMEK' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '0' #
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPI3K' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'AU565' -T 'iPKC' -t '60' #

bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '5.5'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '23'
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '30'
bsub -q generalq -e %J.err -o %J.out -m node25 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'EGF' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'full' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iEGFR' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iMEK' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPI3K' -t '60' #
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '0' #
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '7' #
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '9' #
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '13' #
bsub -q generalq -e %J.err -o %J.out -m node14 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node14 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node14 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'EFM19' -T 'iPKC' -t '60'
#--------------------------
bsub -q generalq -e %J.err -o %J.out -m node12 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node12 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '5.5'
bsub -q generalq -e %J.err -o %J.out -m node12 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node14 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node14 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '23'
bsub -q generalq -e %J.err -o %J.out -m node14 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '30'
bsub -q generalq -e %J.err -o %J.out -m node15 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node15 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node15 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'full' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '14'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'EGF' -t '18'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '14'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iEGFR' -t '18'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '14'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iMEK' -t '18'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '14'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPI3K' -t '18'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '14'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'HCC2218' -T 'iPKC' -t '18'
#--------------------------
bsub -q generalq -e %J.err -o %J.out -m node15 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node15 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '5.5'
bsub -q generalq -e %J.err -o %J.out -m node15 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '23'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '30'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'full' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '60'

bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '5.5'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '23'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '30'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'EGF' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'full' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iEGFR' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iMEK' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPI3K' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'LY2' -T 'iPKC' -t '60'

bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '5.5'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '23'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '30'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'EGF' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'full' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iEGFR' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iMEK' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPI3K' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MACLS2' -T 'iPKC' -t '60'

bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '5.5'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '23'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '30'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'EGF' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'full' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iEGFR' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node24 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iMEK' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node1 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node6 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPI3K' -t '60'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '0'
bsub -q generalq -e %J.err -o %J.out -m node8 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '7'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '9'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '13'
bsub -q generalq -e %J.err -o %J.out -m node9 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '17'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '40'
bsub -q generalq -e %J.err -o %J.out -m node22 -n 5,5 Rscript ./SC1-PLAN-B-MODEL-ext.R -C 'MDAMB436' -T 'iPKC' -t '60'


